name: ASCII Program

on: 
  push

jobs:
  first-job: # Corrected spelling from 'fisrt-job'
    runs-on: ubuntu-latest # FIXED: Changed 'runon' to 'runs-on'
    steps:
      - name: checkout-repo
        uses: actions/checkout@v5

      - name: list repo File
        run: ls -ltra

      - name: Executing Shell Script 
        run: |
          chmod +x ascii-script.sh
          ./ascii-script.sh

      # - name: list and read files
      #   run: |
      #     echo "My first GitHub Action Job"
      #     ls -la
      #     cat README.md

      # - name: install cowsay Program
      #   run: sudo apt-get install cowsay -y

      # - name: Generate ASCII Artwork
      #   run: cowsay -f dragon "run for cover, I am a DRAGON.....RAWA" >> dragon.txt

      # - name: Test existing Files
      #   run: grep -i "dragon" dragon.txt

      # - name: Read File
      #   run: cat dragon.txt

      # - name: list repo File
      #   run: ls -ltra