name: My First Workflow # Changed 'name' capitalization

on: 
  push

jobs:
  first-job: # Corrected spelling from 'fisrt-job'
    runs-on: ubuntu-latest # FIXED: Changed 'runon' to 'runs-on'
    steps:
      - name: checkout-repo
        uses: actions/checkout@v5

      - name: list and read files
        run: |
          echo "My first GitHub Action Job"
          ls -la
          cat README.md

      - name: install cowsay Program
        run: sudo apt-get install cowsay -y

      - name: Generate ASCII Artwork
        run: cowsay -f dragon "run for cover, I am a DRAGON.....RAWA" >> dragon.txt

      # - name: List Files
      #   run: ls -la # Use -la for detailed list

      # - name: Read README File
      #   run: cat README.md # FIXED: Changed capitalization to standard 'README.md'